### ISSUE TITLE
What's the difference with broot?

### ISSUE THREAD

**Issue by magnetophon** [dduan/tre#29]
This is not really an issue, but I was just wondering if you knew about [broot](https://github.com/Canop/broot/).
At first sight, the projects are almost identical: an improved tree, written in rust.
Have you considered joining them?
Judging by number of commits, which is of course not a foolproof method, they seem to be further along.
I hope I'm not stating the obvious or offending you by saying this!

**Comment by dduan** [comment]
I'm not sure what to do about this.
